services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: prmse_admin
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: prmse_db
      MYSQL_USER: prmse
      MYSQL_PASSWORD: prmse_db
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend

  # server:
  #   image: server:latest
  #   container_name: server
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./config.toml:/server/config.toml
  #   depends_on:
  #     - mysql
  #     - minio
  #   networks:
  #     - backend

networks:
  backend:
    driver: bridge
