services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: prmse_admin
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001" 

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: prmse_db
      MYSQL_USER: prmse
      MYSQL_PASSWORD: prmse_db
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  
  worker:
    image: worker:latest
    container_name: worker
    with nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: host

  server:
    image: server:latest
    container_name: server
    volumes:
      - ./config.toml:/server/config.toml
    depends_on:
      - mysql
      - minio
      - worker
    network_mode: host