[app]
Port = 8080

[database]
Path = "server.db"

[worker]
Endpoints = ["http://localhost:8080"]
Cpu = false

[minio]
Endpoint = "localhost:9000"
AccessKey = "root"
SecretKey = "xsd1998715"
DefaultBucket = "prmse-ct"