[app]
Port = 8080

[database]
Path = "server.db"

[worker]
Endpoints = ["http://localhost:8080", "http://localhost:8081"]

[minio]
Path = "server.db"
Endpoint = "http://localhost:9000"
AccessKey = "root"
SecretKey = "xsd1998715"