# Build stage
FROM golang:1.24.3-alpine3.21 AS builder

WORKDIR /server

# Copy the rest of the source code
COPY . .

# Install dependencies
RUN go mod tidy

# Build the binary
RUN go build -o /go/bin/app server/cmd

# Runtime stage
FROM alpine:3.21

WORKDIR /server

RUN apk add --no-cache bash

COPY --from=builder /go/bin/app ./app
COPY ./wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x /usr/local/bin/wait-for-it

# Define the volume for configuration file (to be mounted later)
VOLUME ["/app"]

EXPOSE 8080
ENTRYPOINT ["/usr/local/bin/wait-for-it", "mysql:3306", "-t", "60", "--", "/usr/local/bin/wait-for-it", "minio:9000", "-t", "60", "--", "./app"]


