// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"net/http"
	"server/internal/data"
	"server/internal/data/db"
	"server/internal/data/storage"
	"server/internal/handlers"
	"server/internal/rpc"
	"server/internal/schedule"
	"server/internal/services"
)

// Injectors from wire.go:

func wireApp() (*http.Server, error) {
	gormDB, err := data.NewDatabase()
	if err != nil {
		return nil, err
	}
	tasksRepo := db.NewTasksRepo(gormDB)
	client, err := data.NewMinioClient()
	if err != nil {
		return nil, err
	}
	miniRepo := storage.NewMiniRepo(client)
	tasksService := services.NewTasksService(tasksRepo, miniRepo)
	tasksHandler := handlers.NewTasksHandler(tasksService)
	dicomService := services.NewDicomService(miniRepo, tasksRepo)
	dicomHandler := handlers.NewDicomHandler(dicomService)
	v := rpc.NewRpcClient()
	tasksScheduler := schedule.NewTasksScheduler(tasksRepo, v, miniRepo)
	tasksCleaner := schedule.NewTaskCleaner()
	server := NewServer(tasksHandler, dicomHandler, tasksScheduler, tasksCleaner)
	return server, nil
}
