// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"server/internal/data"
	"server/internal/data/db"
	"server/internal/data/storage"
	"server/internal/handlers"
	"server/internal/rpc"
	"server/internal/schedule"
	"server/internal/services"
)

// Injectors from wire.go:

func wireApp() (*gin.Engine, error) {
	gormDB, err := data.NewDatabase()
	if err != nil {
		return nil, err
	}
	tasksRepo := db.NewTasksRepo(gormDB)
	tasksService := services.NewTasksService(tasksRepo)
	tasksHandler := handlers.NewTasksHandler(tasksService)
	v := rpc.NewRpcClient()
	client, err := data.NewMinioClient()
	if err != nil {
		return nil, err
	}
	miniRepo := storage.NewMiniRepo(client)
	tasksScheduler := schedule.NewTasksScheduler(tasksRepo, v, miniRepo)
	engine := NewServer(tasksHandler, tasksScheduler)
	return engine, nil
}
