# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x03rpc\"L\n\x10InferenceRequest\x12\x0e\n\x06series\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0b\n\x03\x63pu\x18\x04 \x01(\x08\"3\n\x11InferenceResponse\x12\x0e\n\x06series\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t2F\n\x06Worker\x12<\n\tInference\x12\x15.rpc.InferenceRequest\x1a\x16.rpc.InferenceResponse\"\x00\x42\x08Z\x06./;rpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006./;rpc'
  _globals['_INFERENCEREQUEST']._serialized_start=21
  _globals['_INFERENCEREQUEST']._serialized_end=97
  _globals['_INFERENCERESPONSE']._serialized_start=99
  _globals['_INFERENCERESPONSE']._serialized_end=150
  _globals['_WORKER']._serialized_start=152
  _globals['_WORKER']._serialized_end=222
# @@protoc_insertion_point(module_scope)
